### ISSUE TITLE
TypeQL query serialisation and deserialisation to avoid reparsing

### ISSUE THREAD

**Issue by haikalpribadi** [vaticle/typeql#114]
## Problem to Solve

Once a query is parsed, we don't want to ever have to reparse it again, if still in the same system.

## Proposed Solution

Serialise the query object to a series of `byte[]` that can be used to reconstruct the query again in constant time.

**Comment by flyingsilverfin** [comment]
This will be solved with a parametrised/templated query rather than serialising a language-specific binary format
