### ISSUE TITLE
Relation is not allowed to form a rule head of rule as it has an ambiguous  role

### ISSUE THREAD

**Issue by adiv5** [vaticle/typeql#122]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Description

I am trying to define a rule in schema,Going by the when-then syntax. I am getting this error:

```Relation [{ ($d, $c) isa one-association; };] is not allowed to form a rule head of rule [x] as it has an ambiguous (unspecified, variable or meta) role```

## Environment

1. OS (where Grakn server runs): Ubuntu 18.04 LTS
2. Grakn version (and platform):Grakn core available on Pip
3. Grakn client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. make a basic schema
2. make rules by when-then logic ( transitive rule, if A->B, B->C then A->C)
3. execute schema.gql
PS: couldn't share the schema file directly but willing to coordinate.

## Expected Output

No errors

## Actual Output

```Relation [{ ($d, $c) isa one-association; };] is not allowed to form a rule head of rule [x] as it has an ambiguous (unspecified, variable or meta) role```

**Comment by flyingsilverfin** [comment]
This should be resolved in version 2.x, thanks for the issue!
