### ISSUE TITLE
Grakn engine infer transitive rules automatically by default

### ISSUE THREAD

**Issue by adiv5** [vaticle/typeql#123]
## Problem to Solve

Would like the graql to infer transitive rules automatically after schema is loaded

## Current Workaround

Currently using Rules to make transitive rules for entities. its painful if the no. of entities increase drastically

## Proposed Solution

once Schema is loaded, an extra task will run to read those entities and form a transitive rule for all combinations. Ofcourse can make this optional functionality but worth investigating.

**Comment by flyingsilverfin** [comment]
Hi there - this issue is not clear: do you want to make all relations transitive by default?
You can do that with 
```
when {
  ($role-1: $a, $role-2: $b) isa $relation;
  ($role-2: $b, $role-3: $c) isa $relation;
} then {
  ($role-1: $a, $role-3: $c) isa $relation;
}
```

**Comment by flyingsilverfin** [comment]
Closing due to unclear intent and age.
