### ISSUE TITLE
Allow concrete roles in abstract relations

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typeql#203]
## Problem to Solve

Presently all roles in an abstract relation are themselves abstract - they need to be subtyped with `as` before they can be used. This makes subtyping relations overly onerous. Often the child roles are entirely unnecessary from a modelling perspective. Consider the following example.

If we have the base type `request`:
```
request sub relation,
  abstract,
  relates subject,
  relates requester,
  relates respondent;
```

We would like to make a friend request where the subject is a `friendship`, but we still have a `requester` and `respondent` inherited from the parent:
```
friend-request sub request,
  owns approved-date,
  relates friendship as subject;
```
But presently we have to subtype all of the roles, inventing quite pointless role subtypes:
```
friend-request sub request,
  owns approved-date,
  relates friendship as subject,
  relates friend-requester as requester,
  relates friend-respondent as respondent;
```

## Current Workaround

Subtype all roles and live with it!

## Proposed Solution

In some way permit relations to have concrete and/or abstract roles. Ideally the user should declare which is abstract and which is concrete, analogous to abstract and implemented methods in an abstract class in OOP.

**Comment by haikalpribadi** [comment]
We can implement this, as follows:
```
request sub relation @abstract,
  relates subject @abstract,
  relates requester,
  relates respondent;
```

This pattern only makes sense for relation and role types, as role types are part of relation types, but it does not apply to other schema properties such as `owns` and `plays`.

**Comment by flyingsilverfin** [comment]
This isstill use highly useful feature we should implement!

**Comment by flyingsilverfin** [comment]
We have implemented concrete roles in abstraction relations by making all roles in relations concrete - we can still go down the route of `@abstract` annotations on roles separately.
