### ISSUE TITLE
Support modifiers (at least the limit) in all type of queries

### ISSUE THREAD

**Issue by izmalk** [vaticle/typeql#284]
## Problem to Solve

To be able to limit the write queries. Let's say I want to delete just one matched thing, not all of them.

Now we only can have `limit` with match/get queries.

## Current Workaround

Do a match/get query with a limit. Memorize the resulting concepts somehow (iid?). Use a separate delete query with the memorized concepts.

## Proposed Solution

Make it possible to use `limit` and possibly other modifiers in the write queries.

For example:
`match {pattern}; limit 1; sort $x;
delete $x isa thing`

## Additional Information

Without sorting we could end up with Russian roulette: if more concepts will be matched that we have `limit` for - we can't guarantee which ones will be deleted (or used for insert, if it's an insert query). Not an argument for denying this behavior, just needs to be documented.

**Comment by flyingsilverfin** [comment]
This has been implemented as of https://github.com/vaticle/typedb/issues/6857

**Comment by flyingsilverfin** [comment]
Looks like it! https://github.com/vaticle/typedb-behaviour/blob/46a16939c1dd94aac6aebc3dd7e50e8280d3dfe5/query/language/modifiers.feature#L861

The Fetch PR was quite bit and did a bunch of things :)
