### ISSUE TITLE
Fetch: add a way to project an item into a list of attributes by label

### ISSUE THREAD

**Issue by dmitrii-ubskii** [vaticle/typeql#320]
## Problem to Solve

We can currently project a matched variable into a single attribute type by using either the attribute type's name as a string, or as a type label. Projection into multiple concrete attributes is impossible without providing full pairs of type labels with corresponding fetch keys (often equal to the label name).

## Current Workaround

```java
variable.map(listOf(
    Pair(Reference.Label.label(attr_type_0), TypeQLFetch.Key.Label.of(attr_type_0)),
    Pair(Reference.Label.label(attr_type_1), TypeQLFetch.Key.Label.of(attr_type_1)),
    ...
))
```

## Proposed Solution

Implement `ProjectionBuilder::Attribute::map(Reference.Label...)`

**Comment by flyingsilverfin** [comment]
Implemented in #322
