### ISSUE TITLE
Graql: basic arithmetic operations

### ISSUE THREAD

**Issue by grabl** [vaticle/typeql#35]
_This issue was originally posted by @haikalpribadi  on 2017-01-18 16:31_.

The ability to perform the following basic functions in graql:
1. Addition
2. Subtraction
3. Multiplication
etc. . .

**Comment by flyingsilverfin** [comment]
Subsumed by issue https://github.com/vaticle/typedb/issues/6654  and implementation https://github.com/vaticle/typedb/pull/6732
