### ISSUE TITLE
TypeQL: query for variables by multiple IDs

### ISSUE THREAD

**Issue by shasha79** [vaticle/typeql#36]
Currently, it is not possible to use multiple IDs within the same query (the workaround is to use multiple variables). Ideally, I would like it to be supported similar to other attributes like that:

match $x id $id; {$id V168040;} OR {$id V118888;}; get;

**Comment by flyingsilverfin** [comment]
We are discouraging use of IIDs for match queries, as users should use their own keys for concepts instead. In this case, we can roll this issue into more advanced predicates as in #https://github.com/vaticle/typeql/issues/213
