### ISSUE TITLE
Graql: distinguish between type clash in file vs schema

### ISSUE THREAD

**Issue by grabl** [vaticle/typeql#40]
_This issue was originally posted by @jmsfltchr  on 2018-07-09 20:47_.

If you make the mistake of already having a concept defined in your keyspace, but try to load a file that declares that concept to have a different type, you get a slightly cryptic error message, like: 
```
 The concept [Base Type [ENTITY_TYPE] - Id [V28736] - Label [led-observation] - Abstract [false] ] is not of type [interface ai.grakn.concept.RelationshipType] 
```
 Allegedly, we should be able to distinguish between a duplicate definition in a file and a pre-existing concept in the current schema.

**Comment by flyingsilverfin** [comment]
This now throws a more intuitive `[TYR01] Invalid Type Read: Invalid concept conversion from 'TYPE' to 'EntityType'.` error
