### ISSUE TITLE
Graql: sub-relationships should be able to declare new roles that does not override one of the roles in the super-relationships

### ISSUE THREAD

**Issue by grabl** [vaticle/typeql#45]
_This issue was originally posted by @haikalpribadi  on 2018-03-27 14:45_.

For example:

general-data-link sub relationship,
    relates linked-data,

special-data-link sub general-data-link,
    relates special-linked-data as linked-data,  # overrides super role
    relates some-reference,                      # new role
    has special-name;

**Comment by flyingsilverfin** [comment]
This feature is enabled as of TypeDB 2.x
