### ISSUE TITLE
Ontologically invalid queries should not be allowed. See example.

### ISSUE THREAD

**Issue by grabl** [vaticle/typeql#48]
_This issue was originally posted by @haikalpribadi  on 2017-04-24 13:31_.

```
 match $a isa cancer; ($a, $b); $b isa mirna; ($b, $c); ($c, $d); $d isa gene; ($d, $e); $d isa drug; offset 0; limit 3; 
```
 In the query above, I defined `$d` to have two types (that are not an abstraction of one another). This query should not be allowed: a) it should return an error that explains why. b) it should not try to execute the traversal.

**Comment by flyingsilverfin** [comment]
Generally, detecting invalid queries in the schema is now caught by type inference before the query is executed in TypeDB as of 2.x
