### ISSUE TITLE
Analytics starting with a match query

### ISSUE THREAD

**Issue by grabl** [vaticle/typeql#49]
_This issue was originally posted by @haikalpribadi  on 2018-04-12 13:47_.

Improve analytics syntax, pass a match query as subgraph.
e.g. degree:
```
match 
$x isa person; 
$y isa movie; 
($x, $y) isa has-cast; 
compute degree; persist true;
```

```
graql.match(
var(“x”).isa(“person”), 
var(“y”).isa(“movie”), 
var().rel(“y”).rel(“x”).isa(“has-cast”)
).compute().degree().execute();
```

This can NOT be done with the current version with TinkerPop.

**Comment by flyingsilverfin** [comment]
Analytics is currently not supported and will eventually be redesigned into a new form.
