### ISSUE TITLE
Graql: Optionally fetch attributes

### ISSUE THREAD

**Issue by grabl** [vaticle/typeql#52]
_This issue was originally posted by Harry Blakiston Huoston  on 2018-08-26 09:06_.

This is a question at first but may turn into a feature request.
Does grakn support any non-strict attribute requests i.e lets say I am fetching personal information belonging to a person that can either be a phone or an address (both separate child entities of a common entity "property") the two will share a field detail (either +447773078736) or (Flat 70) respectively, then the address may have additional attributes (street, province, city, postalCode and country). A query that allowed me to fetch just the detail if the entity is a "phone" and then the detail, street, province, city, postalCode and country if the entity is an "address".

**Comment by flyingsilverfin** [comment]
Optionals feature request is now covered by https://github.com/vaticle/typedb/issues/6322
