### ISSUE TITLE
Graql: Support for lists of arguments (ids, labels, properties)

### ISSUE THREAD

**Issue by grabl** [vaticle/typeql#62]
_This issue was originally posted by @haikalpribadi  on 2018-04-22 22:47_.

We want to implement a new feature in Graql syntax: the ability to provide a set of arguments to a given graql statement. For example, the ability to provide the  following statement in the schema:

```
define person sub entity, has email [unique, max=3];
```

Defining multiple ids:

`match $x isa person; $x id [V123, V456]; get;`

-> useful for KGlib, set-at-a-time reasoning

Defining multiple values:

`match $x has name [Bob, Alice, Stefan]; get`

Defining multiple labels:

`match $x isa $type; $type label [person, animal]; get;`

All these would work as if the multiple elements were defined via a disjunction.

**Comment by alexjpwalker** [comment]
Superseded by https://github.com/vaticle/typeql/issues/213
