### ISSUE TITLE
Make query language more English-like

### ISSUE THREAD

**Issue by neomatrix369** [vaticle/typeql#70]
## Problem to Solve

Graql is still a bit terse for some instances, especially when the rule definitions start becoming more involved. SQL is quite English-like but can become verbose, Graql expresses a lot of the same definitions in shorted constructs but maybe some improvements can be done to meet half-way.

## Current Workaround

Learn the constructs and get acquainted with the language.

## Proposed Solution

Constructs can be arranged in more like a sentence format: subject-verb-object, subject-verb, a number of improvements can be achieved by just rearranging the constructs or maybe renaming them. 

From a technical perspective, it could mean extending or enhancing the parser to understand different formats or maybe extending the vocabulary so it knows more words or similar words. End-users could use the existing format or the new proposed format when writing Graql.

## Additional Information

I'm happy to suggest literal improvements if you can point me to a resource which lists the lexicon/constructs of the Graql language and some examples of usages.

By making Graql more English-like we could definitely help this idea: https://github.com/graknlabs/workbase/issues/153 (I have raised this to help the current idea from the other perspective).

**Comment by flyingsilverfin** [comment]
We're currently happy with the way TypeQL is structured and aren't making dramatic english-like simplifications to it in the next few years
