### ISSUE TITLE
Semantics of rule subtyping if allowed

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typeql#73]
Currently, rules look like any other schema type (eg. Entity, Attribute, Relation). This leads to confusion because they are defined the same way as these types, eg `define newrule sub rule...`, which implies that they may be written in hierarchies themselves. However, we do not have any meaning ascribed to subtyping existing rules.

Core questions: 
1. What does `subtyping` of rules mean semantically? Currently, it is allowed syntactically
2. Should we even allow subtyping rules? 
3. A `rule` is not a concept type (we have no rule type instances, only exist on the schema level for now). So really should a `rule` even exist in the same hierarchy of `Thing` that it sits in now?

**Comment by JRWest2000** [comment]
Could the semantics of rule sub typing be that  
Rule a supertypes Rule b when Rule a is a generalization of Rule b.  
This might lead to the ability to arrange rules into a tree hirackary that would in turn lead to  
the ability to match relevant rules using binary searching and all the performance advantages that intailes.

**Comment by flyingsilverfin** [comment]
we've decided against this and made rules separate schema entities that are not in a type hierarchy - type hierarchies are only used for `Concept` types, which no longer includes Rules
