### ISSUE TITLE
Executing match-get with only anonymous variables should be disallowed

### ISSUE THREAD

**Issue by vmax** [vaticle/typeql#97]
## Description

`match-get` with *only* anonymous variables should be disallowed as executing such a query yields empty concept maps as a result.

## Environment

1. OS (where Grakn server runs): macOS Catalina
2. Grakn version (and platform): 1.6.0
3. Grakn client: client-java
4. Other environment details:

## Reproducible Steps

Execute `match(var().isa(…)).get()`

## Expected Output

Syntax error

## Actual Output

Query executed with empty `ConceptMap`s as a result

**Comment by flyingsilverfin** [comment]
This is solved in TypeQL as of 2.x
